// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HerramientasV2
{
    internal sealed partial class Vsix
    {
        public const string Id = "HerramientasV2.91e6e339-b2e2-496e-ba20-cadb1c208717";
        public const string Name = "HerramientasJFX";
        public const string Description = @"Herramientas para acelerar el desarrollo se incluyen desde generadores de codigo hasta obtencion de ultimas versiones de frameworks js y css";
        public const string Language = "es-ES";
        public const string Version = "4.68";
        public const string Author = "Kankisko";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
