// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HerramientasV2
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string HerramientasV2String = "ba821318-aca7-42eb-9cb4-38498c148933";
        public static Guid HerramientasV2 = new Guid(HerramientasV2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ObtieneUltimaCDN = 0x0200;
        public const int GeneraMetodosEnLinq = 0x0300;
        public const int GeneraMetodosJSDeWS = 0x0400;
        public const int GeneraFormularioJS = 0x0500;
        public const int GeneraServicioRest = 0x0600;
    }
}